apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--dockerfile=/workspace/Dockerfile"
        - "--context=git://github.com/utkarshkgithub/Kue.git"
        - "--destination=docker.io/utkarshkdocker/cloudblog:jenkins"
        - "--verbosity=debug"
        volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
      restartPolicy: Never
      volumes:
      - name: docker-config
        secret:
          secretName: docker-config-secret
